version: '3'
services:
  app:
    build: .
    ports:
      - '7860:7860'
    volumes:
      - ./openoperator.db:/app/openoperator.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SK=${STRIPE_SK}
