version: '3'
services:
  app:
    build: .
    ports:
      - '7860:7860'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STRIPE_SECRET=${STRIPE_SECRET}
    command: python -m openoperator_pro.app
  payment:
    build: .
    command: uvicorn openoperator_pro.tools.payment_proxy:app --host 0.0.0.0 --port 8080
    ports:
      - '8080:8080'
    environment:
      - STRIPE_SECRET=${STRIPE_SECRET}
